# Generated by Django 5.0.1 on 2024-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
