# Generated by Django 5.0.1 on 2024-01-06 19:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptext', '0003_alter_patient_age_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medicine',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
